data:
  LANGSMITH_TRACING: "false"
  LANGSMITH_ENDPOINT: ""
  LANGSMITH_API_KEY: ""
  LANGSMITH_PROJECT: ""
  TAVILY_API_KEY: ""

email:
  ALERT_EMAIL_FROM: "correo@gmail.com"
  ALERT_EMAIL_TO: "correo@galileo.edu"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: 587
  SMTP_USER: "correo@gmail.com"
  SMTP_PASS: "contrase√±a_secreta"
